version: "3.8"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: shop_db
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

  app:
    build: .
    restart: always
    ports:
      - 127.0.0.1:${LOCAL_PORT}:5000
    command: flask run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi:app
      - FLASK_DEBUG=0

volumes:
  db_data:
