"""remove Description model

Revision ID: 0d69e1446e2e
Revises: 22aca011d72c
Create Date: 2021-03-21 13:36:40.769602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d69e1446e2e'
down_revision = '22aca011d72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('descriptions')
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.create_table('descriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='descriptions_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='descriptions_pkey')
    )
    # ### end Alembic commands ###
