"""nullable shop_id

Revision ID: 4c46d379e4cc
Revises: 0d69e1446e2e
Create Date: 2021-03-21 14:57:33.742195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c46d379e4cc'
down_revision = '0d69e1446e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configurations', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configurations', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
