"""empty message

Revision ID: a645c9f9a0d6
Revises: 4c46d379e4cc
Create Date: 2021-05-13 15:05:38.331487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a645c9f9a0d6'
down_revision = '4c46d379e4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing1')
    op.add_column('products', sa.Column('vendor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'vendor')
    op.create_table('testing1',
    sa.Column('col', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
