APP_NAME = "test_app"
SERVER_HOSTNAME = "46.101.202.101:8099"
SERVER_BASE_URL = f"http://{SERVER_HOSTNAME}"
INSTALL_REDIRECT_URL = f"{SERVER_BASE_URL}/app_installed"

WEBHOOK_APP_UNINSTALL_URL = f"https://{SERVER_HOSTNAME}/app_uninstalled"
